# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultiChoiceView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultiChoiceView

  pod 'Masonry','1.0.2'

  target 'MultiChoiceViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultiChoiceViewUITests' do
    # Pods for testing
  end

end
